#!/bin/bash
# RENDER DEPLOY — COPY & PASTE INSTRUCTIONS

echo "🚀 RENDER DEPLOY SETUP"
echo "====================="
echo ""
echo "STEP 1: Verify files"
ls -1 requirements.txt render.yaml .env.example app_standalone_FINAL.py

echo ""
echo "STEP 2: Push to GitHub"
echo "─────────────────────"
echo "If not already done:"
echo ""
echo "git init"
echo "git add ."
echo "git commit -m 'GDPR diagnostic system - production ready'"
echo "git branch -M main"
echo "git remote add origin https://github.com/YOUR_USER/diagnostico-financiero.git"
echo "git push -u origin main"
echo ""
echo "STEP 3: Deploy on Render"
echo "───────────────────────"
echo "1. Go to render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect GitHub → Select repo"
echo "4. Render auto-detects render.yaml ✓"
echo "5. Click 'Deploy'"
echo ""
echo "STEP 4: Wait ~3-5 minutes"
echo "────────────────────────"
echo "Status will change from 'Building' → 'Live'"
echo "You'll get: https://gdpr-diagnostic-api.onrender.com"
echo ""
echo "STEP 5: Test"
echo "───────────"
echo "curl https://gdpr-diagnostic-api.onrender.com/health"
echo ""
echo "Done! Tell me the URL and I'll run all 8 tests."
